name: Frontend CI (Next.js)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: todo-react-web

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # 🔧 Setup Node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: todo-react-web/package-lock.json

      # 📦 Instalar dependências
      - name: Install dependencies
        run: npm install

      # 🧹 Lint
      - name: Lint
        run: npm run lint

      # 🏗️ Build (garante que não quebra)
      - name: Build
        run: npm run build